In [31]:
list = [1,2,3,45,6,7,8,99]
list.remove(1)
print(list)


[2, 3, 45, 6, 7, 8, 99]


In [32]:
fruits =["cherry","banana","apple","orange","grapes"]
fruits.pop()
print(fruits)

print(fruits)

['cherry', 'banana', 'apple', 'orange']
['cherry', 'banana', 'apple', 'orange']


In [33]:
fruits.append("vegetables")
print(fruits)
fruits.insert(2,"blueberry")
print(fruits)

['cherry', 'banana', 'apple', 'orange', 'vegetables']
['cherry', 'banana', 'blueberry', 'apple', 'orange', 'vegetables']


In [34]:
num=[1, 2,3 , 4,5 ,6 ,7,8,9]
array=[]
for num in number:
    array = num
   
print(array)

NameError: name 'number' is not defined

In [ ]:
even_number=[ num for num in range(10) if num%2==0]
print(even_number)

[0, 2, 4, 6, 8]


In [ ]:
words = ["abhishek","akash","aman","ayush"]
lenghts=[len(word) for word in words ] 
print(lenghts)

[8, 5, 4, 5]


In [ ]:
### List conversion from touple

touple=[1,2,3,4,5]
lists= list(touple)
type(lists)

print(touple[:5])

conactination=touple+lists
print(conactination)
type(conactination)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


list

In [ ]:
nums=[1 , 2 ,3 ,4 ,5 ,6]
### Unpacking In Touple
packed_touple = "hello", True,345

x , y , z = packed_touple
print(x)
print(y)
print(z)

hello
True
345


In [ ]:
numbers = (1 ,2 ,3 ,4 , 5,6,7)
first , *second,third=numbers

print(first)
print(second)
print(third)

1
[2, 3, 4, 5, 6]
7


In [ ]:
##nested listss

lst = [["Abhishek","Akash","Aman"],[True,False, True],[1 , 2,3 ,4 ,5]]
print(lst[0])
print(lst[0][1])
print(lst[0][:3])

['Abhishek', 'Akash', 'Aman']
Akash
['Abhishek', 'Akash', 'Aman']


In [ ]:
## nested touple

nested_touple = (("Abhishek","Akash"),(True),(456))
nested_touple[0]

('Abhishek', 'Akash')

In [ ]:
## iterating over nested touple

for item in nested_touple:
    print(item)

('Abhishek', 'Akash')
True
456


SETS IN PYTHON 
sets are built in data type in python used to store collections of uniques items, They are unorederd meaning that the elements do not follow a specific order , and they fo not allow duplicate elememnts , sets are useful for membership tests , eleminating duplicate entries and performing mathematical set operators like union , intersection , difference and symmetric difference 

In [ ]:
def change_case(str):
    return str.upper()

res =change_case("abhishek")
print(res)

ABHISHEK


In [ ]:
lists = ("Abhishek","akash","aman")

def change_str(list):
   return [ item.upper() for item in lists]
    
result= change_str(lists)

print(result)


['ABHISHEK', 'AKASH', 'AMAN']


In [ ]:
#Chexking if a word is plaindrom or not 
def is_palind(str):
    str = str.lower()
    return str == str[::-1]

ans = is_palind("Aba")
print(ans)

True


In [ ]:
import time

# Step 1: Define the decorator
def timer_decorator(func):
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(f"Time taken by '{func.__name__}': {end - start:.4f} seconds")
        return result
    return wrapper

# Step 2: Create a function that does something complex
@timer_decorator
def complex_calculation(n):
    total = 0
    for i in range(n):
        total += i ** 2  # some heavy computation
    return total

# Step 3: Test with different inputs
print(complex_calculation(10000))
print(complex_calculation(100000))
print(complex_calculation(1000000))


Time taken by 'complex_calculation': 0.0020 seconds
333283335000
Time taken by 'complex_calculation': 0.0150 seconds
333328333350000
Time taken by 'complex_calculation': 0.1670 seconds
333332833333500000


In [ ]:
from package.math import addition
addition(5,4)


9

In [ ]:
with open("example.txt",'r') as file:
    content = file.read()
    print(content)


hii i am abhishek
hii there


In [ ]:
def char_word_count(file_path):
    with open(file_path,'r') as file:
        lines = file.readlines()
        len_count=len(lines)
        word_count= sum((len(line.split()))for line in lines)
        char_count= sum( len(line)for line in lines)

    return len_count , word_count , char_count

file_path="example.txt"
lines , words , chars = char_word_count(file_path)    
print(f"line{lines}, words{words} ,chars{chars}")

line3, words14 ,chars67


In [ ]:
#exception handling 
try:
    num1 =int(input("enter the number"))
    num2 =int(input("Enter second number "))
    result = num1/num2
except ZeroDivisionError:
    print("Please enter second value greater than zero")
except Exception as abhi:
    print(abhi)
else:
    print(f"code gets executed and the answer is {result}")    



Please enter value greater than zero


In [ ]:
#file handling using excpetion tricks
try:
    file=open('example.txt','r')
    content=file.read()
except Exception as ex:
    print(ex)
else:
    print(content)
finally:
    file.close()            

hii i am abhishek
hii there
brother i am lost brother in the chaos 


In [ ]:
def key_value_find(my_dict, key):
    try:
        if key in my_dict:
            value = my_dict[key]
        else:
            raise KeyError(f"'{key}' not found in dictionary")
    except Exception as ex:
        print("Error:", ex)
    else:
        print(f"The value is {value}") 
    finally:
        print("Code execution completed")

# Sample dictionary
dicts = {
    "name": "Abhi",
    "class": 8
}             

key_word = "class"

key_value_find(dicts, key_word)


The value is 8
Code execution completed


In [ ]:
##Class and Objects {OOPS}
#Class - an class is an blueprint for creating objects , attributes , method

class Car: #Name of that partticular class
    ##It is the constructor
    def __init__(self , name , windows):
        self.name =name ## These two are the attributes of the particular class
        self.windows=windows 

    ##We can create methods for that class also   
    def self_Drive(self):
        print(f"This {self.name} car is autonomous car which can drive itself")
        #So finally we have cretaed a class which have some attributes and methods over there
        ## now we can use it 
car1=Car("bmw",4)
print(car1.windows)
car1.self_Drive()  
car2 =Car("TATA Nano" ,5)
car2.self_Drive()
print(car2.name ,car2.windows)

4
This bmw car is autonomous car which can drive itself
This TATA Nano car is autonomous car which can drive itself
TATA Nano 5


In [ ]:
class bankAccount:
    def __init__(self , owner,balance=0):
        self.owner=owner
        self.balance=balance
    def Deposit(self ,amount):
        self.balance =self.balance + amount
        print(f"You have deposited {amount} now your account have {self.balance} money")
    def withDraw(self , amount):
        if amount > self.balance:
            print("Your account doesn't have sufficient funds")
        else:
            self.balance = self.balance - amount
            print(f"you have withdraw {amount} Now your account have {self.balance} fund")
    def total_balance(self):
        return self.balance 

account_1=bankAccount("Abhishek",5000) 
account_1.Deposit(4000) 
account_1.withDraw(5000)      
account_1.total_balance()        


You have deposited 4000 now your account have 9000 money
you have withdraw 5000 Now your account have 4000 fund


4000

In [ ]:
#Assignment-1
class Car:
    def __init__(self,name ,model , year):
        self.name=name
        self.model=model
        self.year=year
    def start_engine(self):
        print(f"Your car {self.name} has just started")    

car1 =  Car("BMW" ,"X-Series" ,2025)
print(car1.name)
print(car1.model)
print(car1.year)
car1.start_engine()


BMW
X-Series
2025
Your car BMW has just started


In [ ]:
class Student:
    def __init__(self , name , age ):
        self.name = name
        self.age= age
    def check_result(self,marks):
        if(marks >= 60 and marks <70):
            print("You have been passed")
        elif(marks >70 and marks<90):
            print(f"great {self.name} you got good marks")
        elif(marks >= 90 and marks<=100):
            print(f"congrats {self.name} you have top tha class")  
        else:
            print("You enter the wrong data")
student_1=Student("Abhishek",19)
student_1.check_result(90)                   



congrats Abhishek you have top tha class


In [ ]:
class Calculator:
    def __init__(self, number):
        self.number = number
        self.value = number  # Initialize the value attribute with the initial number
        
    def addition(self, number):
        self.value += number  # Use the passed number for addition
        return self
    
    def subtraction(self, number):
        self.value -= number  # Use the passed number for subtraction
        return self
    
    def division(self, number):
        if number != 0:
            self.value /= number  # Use the passed number for division
            return self
        else:
            print("Zero can not be divided by any number")
            return self

first_calc = Calculator(100)
result = first_calc.addition(10).subtraction(5).division(1).value  # Access the final value
print(result)

105.0


In [ ]:
##Inheritance in OOPS
#type - herbivores , carnivores , omnivores
#movement - whether animal flies or walk on foot
class Animal:
    def __init__(self , type , movement):
        self.type =type
        self.movement =movement

    def speak(self,sound):
        print(f"the animal speaks like {sound}")    


In [ ]:
class Dog(Animal):
    def __init__(self,type,movement ,name,owner):
        super().__init__(type ,movement)
        self.name= name
        self.owner=owner
    def charCter(self ,char_cter):
        print(f"My dog {self.name} is good in nature")  

dog_1=Dog("Ominvores","Footwalker","Ronny","Abhishek") 
print(f"my dog {dog_1.name} is {dog_1.type} ")
dog_1.charCter("Nice")
print(dog_1.name)      
dog_1.speak("Woof Woof")

my dog Ronny is Ominvores 
My dog Ronny is good in nature
Ronny
the animal speaks like Woof Woof


In [ ]:
#Parent classs
class shape:
    def shape(self):
        return"hellow"    

#DErived class 1
class Rectangle(shape):
    def __init__(self, height, width):
        self.height=height
        self.width=width

    def area(self):
        return self.height * self.width
#Derived class
class Circle(shape):
    def __init__(self, radius):
        self.radius=radius 

    def area(self):
        return 3.14*self.radius*self.radius
    

##Function that defines polymorphism    
def print_area(shape):
    print(f"the area is {shape.area()}")

rectangle=Rectangle(10,5)
circle=Circle(9)    

print_area(rectangle)
print_area(circle)



the area is 50
the area is 254.34


In [ ]:
class Number:
    def __init__(self, num):
        self.num = num
    
    def __add__(self, other):
        return Number(self.num + other.num)

n1 = Number(5)
n2 = Number(10)

result = n1 + n2  # Overloading the "+" operator
print(result.num)  # Output: 15

15


In [ ]:
##Polymorphism using abstract method
from abc import ABC , abstractmethod

class Vehicle(ABC):
    @abstractmethod
    def start_engine(self):
        pass
##derived vlass 1    
class Motorcycle(Vehicle):
    def start_engine(self):
        print("The Motorcycle engine started ")

 ##derived class 2
class Car(Vehicle):
    def start_engine(self):
        print("Car engine get started")

##funcrtion that demonstarte the polymorphism
def start_vehicle(Vehicle):
    print(Vehicle.start_engine())

car = Car()
start_vehicle(car)





Car engine get started
None


In [ ]:
##ENCAPSULATION ~~
class Person:
    def __init__(self , name ,age):
        self.__name=name#Private varibale
        self.__age=age#private variable
def get_person(person):
    return person.__name

person=Person("Abhishek",19) 
get_person(person) 
     
     


AttributeError: 'Person' object has no attribute '__name'

In [ ]:
dir(Person)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

In [ ]:
class Person:
    def __init__(self , name ,age):
        self.name=name#Public varibale
        self.age=age#public variable
def get_person(person):
    return person.__name

person=Person("Abhishek",19) 
get_person(person) 
     
     


In [ ]:
##Encapsulation with Getter and setter method
class Person:
    def __init__(self ,name,age):
        self.__name=name  ##Private Access modifier
        self.__age=age ##Private variable

    ##Getter method
    def getter(self):
        return self.__name
    ##setter method
    def setter(self,name):
        self.__name =name

    def get_age(self):
        return self.__age 
    def set_age(self,age):
        if age >0:
           self.__age=age 
        else:
            print("age can not be negative")

person = Person("Abhishek", 56)
print(person.get_age())             

56


##Abstraction in Python

In [ ]:
Abstraction is the concept of hiding  the complex implementation details and showing only the necessary features of an object , This helps in reducing programming complexity and effort 

In [ ]:
from abc import ABC , abstractmethod

##Abstarct base class 
class Vehicle (ABC):
    def drive(self):
        print("The vehicle is used for driving")

    @abstractmethod
    def start_engine(self):
        pass 

class Car(Vehicle):
    def start_engine(self):
        print("The car get started ")

    def operate_vehicle(vehicle):
        vehicle.start_engine()

car = Car()
car.drive()
car.start_engine()            
           

The vehicle is used for driving
The car get started 


In [ ]:
class Animal:
    def __init__(self,name , species):
        self.name=name
        self.species=species
    def print_name(self):
        print(self.name)    

##Derived Class
class Dog(Animal):
    def __init__(self,name,species,breed):
        super().__init__(name , species)
        self.breed = breed
    def __str__(self):
        print(f"Hi i am a dog my name is {self.name} and i am form this {self.breed} breed ")    
    def sound_(self):
        print("I used to bark likebhau bhau")


dog = Dog("Tonny","Rot-viller","Homo-sapiens") 
dog.print_name()
dog.__str__()
dog.sound_()
     
        



Tonny
Hi i am a dog my name is Tonny and i am form this Homo-sapiens breed 
I used to bark likebhau bhau


In [ ]:
class Runner:
    def __init__(self, run):
        self.run = run

    def runner(self):
        print(f"Yes, it's {self.run} that I am a runner.")

class Walker:
    def __init__(self, walk):
        self.walk = walk

    def walker(self):
        print(f"Yes, it's {self.walk} that I am also a walker.")

class Athelete(Runner, Walker):
    def __init__(self, name, run, walk , train_hours):
        Runner.__init__(self, run)  # Explicitly call Runner's constructor
        Walker.__init__(self, walk)  # Explicitly call Walker's constructor
        self.name = name
        self.train_hours=train_hours
        print(f"Athelete Name: {self.name}")

    def inherited(self):
        self.runner()  # Calling Runner's method
        self.walker()  # Calling Walker's method
    def walker(self):
        print(f"Yes i can also walk along with running")

    def train_time(self):
        print(f"Yes i train for that {self.train_hours} hours")    
# Creating an instance of Athelete
athelete = Athelete("Abhishek", "fast running", "slow walking",4)
athelete.inherited()
athelete.train_time()



Athelete Name: Abhishek
Yes, it's fast running that I am a runner.
Yes i can also walk along with running
Yes i train for that 4 hours


In [ ]:
class A:
    def __init__(self):
        pass
    def show(self):
        print("Inherited from Class A")

class B(A):
    def __init__(self,):

        pass
    def show(self):
        print("Yes i m being called from class B")

class C(A):

        

## magic methods in python

In [49]:
class A:
    pass

person = A()
dir(person)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

So these are all tye magic methods in python

In [50]:
class Person:
    def __init__(self,name ,age):
        self.name=name
        self.age=age
    def __str__(self):
        return f"{self.name} ,{self.age}"
    def __repr__(self):
        return f"{self.name}, {self.age}"
Abhishek=Person("Abhi",19)
print(Abhishek)        

Abhi ,19


###Method Overloading

Custom Exception

In [51]:


year=int(input("Enter the year of born"))
age = 2024 = year

try:
    if age >=20 and age <= 30:
        print("You're valid to fill the exam form")
    else raise dobexception:   
except dobexception:
    print('Sorry you are unable to fill the exam form ') 

SyntaxError: cannot assign to literal (2200972578.py, line 2)

##Method overriding

In [ ]:
class A:
    def show(self):
        print("Method from A")

class B(A):
    def show(self):
        super().show()
        print("Method from B")

class C(B):
    def show(self):
        super().show()
        print("Method from C")

obj = C()
obj.show()

Method from A
Method from B
Method from C


QUESTION -1 

In [ ]:
class Shape:
    def __init__(self):  # Base constructor
        pass
    
    def area(self):
        pass  # Abstract method for area

class Rectangle(Shape):
    def __init__(self, length, breadth):
        super().__init__()  # Calling parent constructor
        self.length = length
        self.breadth = breadth
    
    def area(self):
        return self.length * self.breadth

class Circle(Shape):
    def __init__(self, radius):
        super().__init__()  # Calling parent constructor
        self.radius = radius
    
    def area(self):
        return 3.14 * self.radius * self.radius  # Correct formula for circle area

def print_area(shape):
    print(f"The area is {shape.area()}")

# Creating and testing objects
circle_obj = Circle(50)
print_area(circle_obj)  # Output: The area is 7850.0
rect_obj=Rectangle(34,56)
print_area(rect_obj)

def describe_area(arg):
    print(f"{arg.area()}")
describe_area(circle_obj)


The area is 7850.0
The area is 1904
7850.0


In [ ]:
from abc import ABC, abstractmethod

# 🔹 Abstraction: Abstract class to define account structure
class BankAccount(ABC):
    def __init__(self, account_holder, balance):
        self.account_holder = account_holder  # Public attribute
        self.__balance = balance  # Private attribute

    @abstractmethod
    def calculate_interest(self):
        pass  # Must be implemented in subclasses

    # 🔹 Encapsulation: Methods to access private data safely
    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            return f"Deposited {amount}. New balance: {self.__balance}"
        return "Invalid deposit amount!"

    def get_balance(self):
        return f"Balance: {self.__balance}"

# 🔹 Polymorphism: Different account types implementing their own logic
class SavingsAccount(BankAccount):
    def calculate_interest(self):
        return f"Interest for Savings Account: {self.get_balance()} * 4%"

class CurrentAccount(BankAccount):
    def calculate_interest(self):
        return f"Interest for Current Account: {self.get_balance()} * 2%"

# Function demonstrating polymorphism
def print_interest(account):
    print(account.calculate_interest())

# Creating objects and testing encapsulation & polymorphism
savings = SavingsAccount("Alice", 5000)
current = CurrentAccount("Bob", 10000)

print(savings.deposit(2000))  # Encapsulation example
print_interest(savings)       # Polymorphism example
print_interest(current)       # Polymorphism example

Deposited 2000. New balance: 7000
Interest for Savings Account: Balance: 7000 * 4%
Interest for Current Account: Balance: 10000 * 2%


Question 1

In [ ]:
##POLYMORPHISM


class Shape:
    def __init__(self):
        pass
    def area():
        return "the area is"
class Circle(Shape):
    def __init__(self,radius):
        self.radius=radius
    def area(self):
        print(f"The area of the circle is {3.14 * self.radius * self.radius}")

class Rectangle(Shape):
    def __init__(self,length ,height):
        self.length=length
        self.height=height
    def area(self):
        print(f"The area is {self.length * self.height}");

area_cir = Circle(5)
area_cir.area()   
area_rect =Rectangle(4,5)
area_rect.area()               
        
def describe_shape(args):
    print(f"{args.area()}")
describe_shape(area_cir)

        

The area of the circle is 78.5
The area is 20
The area of the circle is 78.5
None


QUESTION 2

In [ ]:
from abc import ABC, abstractmethod  # Import ABC and abstractmethod

# Abstract base class
class Vehicle(ABC):
    def __init__(self, fuel_type):
        self._fuel_type = fuel_type  # Renamed the attribute to avoid conflict

    @abstractmethod
    def start_engine(self):  # Abstract method
        pass

# Derived class 1
class Car(Vehicle):
    def start_engine(self):
        print("The car engine has started")

    def get_fuel_type(self):  # Renamed the method to avoid conflict
        return f"Your car fuel type is {self._fuel_type}"

# Derived class 2
class Bike(Vehicle):
    def start_engine(self):
        print("The bike engine has started")

    def get_fuel_type(self):  # Renamed the method to avoid conflict
        return f"Your bike fuel type is {self._fuel_type}"

# Create instances and call the method
start_car = Car("Diesel")  # Pass "Diesel" as a string
start_car.start_engine()
print(start_car.get_fuel_type())  # Call the renamed method

start_bike = Bike("Petrol")  # Pass "Petrol" as a string
start_bike.start_engine()
print(start_bike.get_fuel_type())  # Call the renamed method

The car engine has started
Your car fuel type is Diesel
The bike engine has started
Your bike fuel type is Petrol


In [ ]:
class BankAccount():
    def __init__(self,acc_holder ,acc_number ,amount):
        self.acc_holder=acc_holder
        self.__acc_number=acc_number
        self.__amount=amount
    def add_money(self,depo_amount):
        self.depo_amount=depo_amount
        self.__amount +=depo_amount
        print(f"you have deposited {self.depo_amount} amount")
    def withdrawl(self,with_draw):
        self.with_draw=with_draw
        self.__amount -=with_draw
        print(f"You have withdraw {self.with_draw} amount")    
    def gettotal(self):
        print(f"Your total account balance is {self.__amount}")
    
   
acc =BankAccount("Abhi",234089,5000)
acc.gettotal()
acc.withdrawl(5000)
acc.gettotal()
acc.add_money(10000)
acc.gettotal()

Your total account balance is 5000
You have withdraw 5000 amount
Your total account balance is 0
you have deposited 10000 amount
Your total account balance is 10000


Iterator in pyhton


In [ ]:
my_list = [1,2,3,4,5,6,8]
iterator=iter(my_list)

type(iterator)
iterator

In [ ]:
next(iterator)

StopIteration: 

Generators in python


In [ ]:
def gen_rator():
    yield 1
    yield 2
    yield 3
gen = gen_rator()
next(gen)    
next(gen)
next(gen)



3

Function Copy


function copy is a process in which we define a function and call it and we initialise the calling method in to another variable this is how a process been done

In [ ]:
def wel_come():
    print("fuck you ")
well =wel_come
well()
wel_come()
##This is how a function copy gets done 

fuck you 
fuck you 


Closure

A function inside a function and the variale declared inside the first func can be used in nested function this property called the closure

In [ ]:
##example
def fun_ction():
    msg = "Hello tehre i'm abhishek"
    def sub_func():
        print("Welcome to home")
        print(msg)
        print("Hello motherfucker")
    return sub_func()    
fun_ction()

Welcome to home
Hello tehre i'm abhishek
Hello motherfucker


In [ ]:
##another example of passing the built in function as the parameter lets see what happen
def abhi_shek(func):
    func("Hey son how are you")
    def insi_func(func):
        func("Helllo brother")
    return insi_func(print)
abhi_shek(print)    

Hey son how are you
Helllo brother


In [ ]:
def decorator_function(original_function):
    def wrapper_function():
        print("Wrapper executed before", original_function.__name__)
        original_function()
        print("Wrapper executed after", original_function.__name__)
    return wrapper_function

@decorator_function
def say_hello():
    print("Hello!")

say_hello()

Wrapper executed before say_hello
Hello!
Wrapper executed after say_hello


##Decorator

In [ ]:
def functio_n(func):
    print("Hello mister")
    func()
    def sec_func():
        print("hello motherfucker ",func.__name__)
        func()
        print("Hello cowboy",func.__name__)
    return sec_func
@functio_n
def hello_mc():
    print("Helo mf's")
hello_mc()            

Hello mister
Helo mf's
hello motherfucker  hello_mc
Helo mf's
Hello cowboy hello_mc


In [ ]:
class Countdown:
    def __init__(self, start):
        self.current = start

    def __iter__(self):
        return self  # this object is its own iterator

    def __next__(self):
        if self.current < 0:
            raise StopIteration
        value = self.current
        self.current -= 1
        return value

# Using the iterator
c = Countdown(3)
it = iter(c)

print(next(it))  # 3
print(next(it))  # 2
print(next(it))  # 1
print(next(it))  # 0
print(next(it))  # Raises StopIteration


3
2
1
0


StopIteration: 

In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np


arr =np.array([1,2,3,4,5])
print(type(arr))
print(arr)
print(arr.shape)

<class 'numpy.ndarray'>
[1 2 3 4 5]
(5,)


In [ ]:
arr2 = np.array([2,4,6,8,0])
arr2.reshape(1,5) ##1 row and 5 columns

array([[2, 4, 6, 8, 0]])

In [ ]:
arr2=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr2.shape)
print(arr2)

(2, 5)
[[1 2 3 4 5]
 [4 5 6 7 8]]


In [ ]:
np.arange(0,20,3).reshape(1,7)

array([[ 0,  3,  6,  9, 12, 15, 18]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
##idwntity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr =np.array([[1,2,3],[4,5,6]])

print("Array are",arr)
print("array shape",arr.shape)
print("array dimension",arr.ndim)
print("Size (numbr of elemets ):",arr.size)
print("Dataa type",arr.dtype)
print("item size in bytes",arr.itemsize)

Array are [[1 2 3]
 [4 5 6]]
array shape (2, 3)
array dimension 2
Size (numbr of elemets ): 6
Dataa type int64
item size in bytes 8


In [ ]:
##numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

##element wise addition
print("Addition:",arr1 + arr2)

##element wise substraction
print("Substraction",arr1 - arr2)

##element wise multiplication
print("Multiplication",arr1*arr2)

Addition: [11 22 33 44 55]
Substraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]


In [ ]:
##universal function
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))

NameError: name 'np' is not defined

In [ ]:
##exponential
print(np.exp(arr))

##sine
print(np.sin(arr))

#3natural log
print(np.log(arr))

[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
!pip install numpy
import numpy as np
print(np.__version__)

2.2.1


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8],[0,2,4,5]])

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
print(np.__version__)
arr=np.array([[1,2,3,4],[5,6,7,8],[0,2,4,5]])
print(arr)

2.2.1
[[1 2 3 4]
 [5 6 7 8]
 [0 2 4 5]]


In [ ]:
arr[0][3]
print(arr[2])
arr[1][2]

[0 2 4 5]


np.int64(7)

In [ ]:
arr[0:]
arr[2:]

array([[0, 2, 4, 5]])

In [ ]:
print(arr[0:2,2:4])

[[3 4]
 [7 8]]


In [ ]:
arr[0,2]=50
print(arr)

[[ 1  2 50  4]
 [ 5  6  7  8]
 [ 0  2  4  5]]


In [ ]:
import numpy as np
data=np.array([1,2,3,4,5,6,7,8,9,10])
#mean
mean=np.mean(data)
print(mean)

#median
median=np.median(data)
print(median)

#standard deviation
std_dev=np.std(data)
print(std_dev)

#variance
variance=np.var(data)
print("variance:",variance)

5.5
5.5
2.8722813232690143
variance: 8.25


In [ ]:
data =np.array([1,2,3,4,5,6,7,8,9,10])
data[data>5]


array([ 6,  7,  8,  9, 10])

pandas

In [ ]:
import pandas as pd

In [ ]:
data=[1,2,3,4,5,6,7,8,9]
series=pd.Series(data)
print("Series :",series)
print(type(series))

Series : 0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
##series from dictionary elements
data = {'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64


In [ ]:
import pandas as pd

# Creating a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}

# Converting dictionary to DataFrame
df = pd.DataFrame(data)

# Displaying the DataFrame
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris


In [ ]:
#create a dataframe from a list of dictionaries
data=[
    {'Name':"Abhishek",'age':20,"City":"Lucknow"}
    ,
    {'Name':"Abhishek",'age':20,"City":"Lucknow"},
    {'Name':"Abhishek",'age':20,"City":"Lucknow"},
    {'Name':"Abhishek",'age':20,"City":"Lucknow"}
]

df=pd.DataFrame(data)
print(df)
print(type(df))

       Name  age     City
0  Abhishek   20  Lucknow
1  Abhishek   20  Lucknow
2  Abhishek   20  Lucknow
3  Abhishek   20  Lucknow
<class 'pandas.core.frame.DataFrame'>


In [ ]:
pd.read_csv('filename.csv')
pd.head(5) #it will find out the top five data of the file
pd.tail(5)#it willl find outthe bottom five data list

In [ ]:
##accessing data from dataframe
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}
df = pd.DataFrame(data)
df


Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [ ]:
type(df['Name'])

pandas.core.series.Series

In [ ]:
##used to print row index
df.loc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [ ]:
##used to print column index
df.iloc[0][1]

C:\Users\Abhishek\AppData\Local\Temp\ipykernel_22676\2215106252.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]


np.int64(25)

In [ ]:
##Accessing a specified element
df['Name'] 
print(df)
df.at[0,'Name']
df.at[2,'Age']

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris


np.int64(35)

In [ ]:
df.iat[0,0]
df.iat[2,2]

'Paris'

In [ ]:
##adding more column
df['Salary']=[1000,50000,56000]
df

Name  Age      City  Salary
0    Alice   25  New York    1000
1      Bob   30    London   50000
2  Charlie   35     Paris   56000

In [ ]:
##deleting any particular columns from data
df.drop('Salary',axis=1)
##but it will not delete it permanently

Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [ ]:
df
df.drop('Salary', axis=1, inplace=True, errors='ignore')

In [ ]:
df

Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [ ]:
##increamenting age to column 

print(df.info())
print("Before:\n", df['Age'])
df['Age'] = df['Age'] + 1
print("After:\n", df['Age'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None
Before:
 0    31
1    36
2    41
Name: Age, dtype: int64
After:
 0    32
1    37
2    42
Name: Age, dtype: int64


In [ ]:
df.drop(1,inplace=True,errors='ignore')
df

Name  Age      City
0    Alice   32  New York
2  Charlie   42     Paris

In [ ]:
df

Name  Age      City
0    Alice   32  New York
2  Charlie   42     Paris

Data manipulation and Analysis with numpy and pandas 

Data manipulation and analysis are key taks in any data scinece or data analysis project .Pandas provides a wide range of functions for data manipulation and analysis , making it easier to clean , transform and extract isights from data 

In [1]:
import pandas as pd 

In [ ]:
df = pd.read_csv('data.csv') ## used to read data from csv file

In [ ]:
##handling missing values 
df.isnull() ##it returns a boolean value True if any value is null or false if any value is no false


In [ ]:
##we can count even the num of value which are null by using sum method
df.isnull().sum()

In [ ]:
## we can fill the missing values by {0} using fillna method
df_filled=df.fillna(0)

In [ ]:
##filling missing values with the mean of that particular column 
df['Sales_fillNA']=df['Sales'].fillna(df['Sales'].mean())

In [ ]:
#reanming any particular column
df.rename(columns={'Date':'Sales_Dat'})
df.head()

In [ ]:
##changing data type
#converting into float value
df['Value_new']=df['Value'].astype(float)

In [ ]:
# applying a particular method to one of the value of column and change its value
df['New value']=df['Value'].apply(lambda x:x*2) 
# it will add a new column of New value having 2x value

In [ ]:
##Data Aggregating and Grouping
#In pandas, data aggregation and grouping are techniques
#  used to summarize and 
# analyze data efficiently. These operations help in 
# breaking down large datasets into meaningful segments, 
# making it easier to extract insights.

# there are similar example of it 
import pandas as pd

# Creating a sample DataFrame
data = {'Category': ['A', 'B', 'A', 'B', 'A', 'C'],
        'Values': [10, 20, 30, 40, 50, 60]}

df = pd.DataFrame(data)

# Grouping by 'Category' and calculating sum
grouped = df.groupby('Category')['Values'].sum()
mean_val=df.groupby('Category')['Values'].mean()
print(mean_val)
print(grouped)


Category
A    30.0
B    30.0
C    60.0
Name: Values, dtype: float64
Category
A    90
B    60
C    60
Name: Values, dtype: int64


Aggregation in Pandas (agg())
Aggregation functions allow you to apply multiple operations on grouped data. You can use .agg() to perform multiple functions like mean, sum, count, etc., in a single step.


In [4]:
grouped_agg = df.groupby('Category')['Values'].agg(['sum', 'mean', 'count'])

print(grouped_agg)

          sum  mean  count
Category                  
A          90  30.0      3
B          60  30.0      2
C          60  60.0      1
